Resources/README.md

Added Copilot Studio resources (video, blog & code repo).

Added Copilot Studio resources

---

README.md

Added link to the existing MSSQL MCP Server

MSSQL MCP Server

---

README.md

Dev Box MCP is an MCP server for [Microsoft Dev Box](https://azure.microsoft.com/en-us/products/dev-box). It enables natural language interactions for developer-focused operations like managing Dev Boxes, configuring environments, and handling pools.

Added Dev Box MCP to README.md

---

README.md

Add a unicode emoji for Dataverse MCP

Add a unicode emoji for Dataverse MCP

---

README.md

Add Azure Kubernetes Service (AKS) MCP Server

Add Azure Kubernetes Service (AKS) MCP Server

---

Resources/README.md

In this PR I added the new lab of the Copilot Dev Camp about consuming an MCP server from within Microsoft Copilot Studio.

Added lab MCS6 of Copilot Dev Camp

---

eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updated CHANGELOGs ahead of `0.5.9` release.
N/A

Prepare `0.5.9` Azure MCP Server release

---

eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj

Updates Azure MCP Server CHANGELOGs and project version after the `0.5.9` release.
N/A

Updated Azure MCP Server version after `0.5.9` release

---

eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updated CHANGELOGs ahead of 0.5.10 release
N/A

Prepare `0.5.10` release

---

eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj

Updated CHANGELOGs and project version after Azure MCP Server release
N/A

Increment versions after `0.5.10` release

---

Directory.Build.props
eng/pipelines/templates/common.yml
eng/pipelines/templates/jobs/build.yml
eng/pipelines/templates/jobs/integration.yml
eng/pipelines/templates/jobs/release.yml
eng/pipelines/templates/jobs/sign-and-pack-vsix.yml
eng/pipelines/templates/jobs/sign-and-pack.yml
eng/pipelines/templates/steps/publish-to-dev-feed.yml
eng/scripts/Build-Module.ps1
eng/scripts/Compress-ForSigning.ps1
servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj

Includes native packages in build artifacts and pack/release scripts

Publish Native Packages

---

eng/pipelines/templates/jobs/release.yml

The release pipeline is failing given the following error in ADO:
> The 'stages' parameter is not a valid StageList.
/eng/pipelines/templates/jobs/release.yml (Line: 91, Col: 11): Unexpected value 'if eq('True', true)'
This PR fixes the syntax since the parameter is already a boolean

Fix release pipeline

---

.github/CODEOWNERS

Update CODEOWNERS file to bulk rename area-* -> tools-* after @alzimmermsft's label migration from /azure/azure-mcp to /microsoft/mcp

Update CODEOWNERS with new service labels

---

Directory.Packages.props
servers/Azure.Mcp.Server/CHANGELOG.md

Updates Azure.Identity and Azure.Identity.Broker package versions to the latest GA.
Fixes https://github.com/microsoft/mcp/issues/351

Update Azure.Identity and Azure.Identity.Broker package versions

---

.github/CODEOWNERS

Add @microsoft/fabric-mcp to codeowners file

Add @microsoft/fabric-mcp to codeowners file

---

servers/Azure.Mcp.Server/TROUBLESHOOTING.md

Add section in TROUBLESHOOTING.md for resetting stale configuration
Replaces https://github.com/Azure/azure-mcp/pull/774
https://github.com/Azure/azure-mcp/issues/660, https://github.com/Azure/azure-mcp/issues/772

Update troubleshooting markdown

---

.github/CODEOWNERS

Update CODEOWNERS for AKS tools

Update CODEOWNERS for AKS tools

---

docs/new-command.md

Adds a few more guidelines into `new-command.md` based on recent design discussions.

Add additional guidelines into new-command.md

---

eng/pipelines/templates/1es-redirect.yml
eng/pipelines/templates/jobs/build.yml

Enable CodeQL analysis for internal Linux builds.

Add CodeQL support for internal Linux builds

---

eng/scripts/Pack-Nuget.ps1

Adds NOTICE.txt and LICENSE to packed .nupkgs
https://github.com/microsoft/mcp-pr/issues/48

Add NOTICE.txt and LICENSE to the nuget package

---

docs/azmcp-commands.md
docs/e2eTestPrompts.md
eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
eng/vscode/README.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/README.md

- Updates CHANGELOGs and READMEs
- Re-orders markdown documentation around commands (tools) and prompts
N/A

Prepare 0.7.0 release

---

eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj

Updates CHANGELOGs, READMEs and project version.
N/A

Increment versions after `0.8.0` release

---

README.md

Adds the official NuGet MCP server to the list https://github.com/microsoft/mcp/issues/29

Add NuGet MCP Server information to README

---

eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updated CHANGELOGs and READMEs ahead of the `0.8.2` release
N/A

Prepare `0.8.2` release

---

docs/e2eTestPrompts.md
eng/tools/ToolDescriptionEvaluator/prompts.json
tools/Azure.Mcp.Tools.Postgres/src/Commands/Database/DatabaseQueryCommand.cs
tools/Azure.Mcp.Tools.Postgres/src/Commands/Server/ServerParamSetCommand.cs

Enhance the tool description for postgre sql to have a confidence score of > 0.5
azmcp_postgres_server_param_set:
azmcp_postgres_database_query:

Enhance the tool description for postgre sql

---

.github/CODEOWNERS

Fixed Kusto owner to list prvavill as primary owner

Fixed Kusto owner to list prvavill as primary owner

---

docs/azmcp-commands.md
docs/e2eTestPrompts.md
eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updates CHANGELOGs, versions and docs to reflect the latest changes compared to the previous release.
N/A

Preparing `0.8.3` release

---

docs/Authentication.md

- Add Cosmos DB SQL data-plane RBAC setup instructions to the authentication guide
- Includes PowerShell (user) and Bash (service principal) examples
- Notes on role choices, scope, and RBAC propagation
- Update docs/Authentication.md:
- New section: 'Azure Cosmos DB (RBAC for SQL data plane)'
- Guidance for built-in roles (Data Reader/Contributor) and account-scope assignments
- Verified formatting and links locally
- Will rely on doc reviewers and Cosmos tool owners to validate guidance
Fixes #140

docs: add Cosmos DB RBAC auth instructions to Authentication.md

---

tools/Azure.Mcp.Tools.Deploy/src/Commands/App/LogsGetCommand.cs

Enhance tool description of Deploy to make the description clearer. The earlier tool description is too generic and doesn't emphasize that it's specifically for Azure Developer CLI (azd) deployed applications. 
Current score-
Previous score-
https://github.com/microsoft/mcp/issues/624

Enhance tool description of Deploy

---

core/Azure.Mcp.Core/src/Areas/Server/Commands/ServiceCollectionExtensions.cs
servers/Azure.Mcp.Server/CHANGELOG.md

The `CommandGroupServerProvider `and `RegistryServerProvider `are instantiated by `CommandGroupDiscoveryStrategy` and `RegistryDiscoveryStrategy` during the discovery phase, so there’s no need to register these provider types with the DI container.

Remove unnecessary DI registration for IMcpServerProvider instance

---

eng/pipelines/templates/jobs/analyze.yml
eng/scripts/Pack-Npm.ps1
eng/scripts/Pack-Nuget.ps1
eng/scripts/Pack-Vsix.ps1
eng/scripts/Process-PackageReadMe.ps1
servers/Fabric.Mcp.Server/README.md

- Validate All Package Readme files rather than a single file specific to a server.
- Fix Fabric.Mcp.Server README TOC
- none

Verify all package README.mds in Pull Request Run

---

servers/Azure.Mcp.Server/README.md

- Remove IntelliJ link from README for vsix
- none

Remove InteliJ link for vsix README.md

---

servers/Azure.Mcp.Server/README.md

We're at 43 azure service areas now. Bump the text from 30+ to 40+

Change 30+ to 40+ in README
