Resources/README.md

Fixed order of the columns in code resource and added language (typescript)

Fixed order of the columns in resource

---

README.md

Clarify the MCP server section and add new server details for Microsoft MCP servers, including specific repositories and descriptions for Markitdown and Clarity MCP servers. Introduce a section for starter templates related to MCP.

Update README.md for MCP server clarity and details

---

README.md

This pull request updates the `README.md` file to include information about the Azure DevOps MCP Server. The change introduces a new section with documentation and a description of this server's capabilities.
Key addition:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R83-R88): Added a new section titled "Azure DevOps MCP Server" with documentation and a description explaining how the server integrates Azure DevOps artifacts into AI workflows.

Adding Azure DevOps MCP Server to list of available in README.MD

---

eng/pipelines/templates/jobs/docker.yml
eng/pipelines/templates/jobs/release.yml

We are using `gh api`. The `gh api` does not support `**` pattern matching.
Therefore, we need to update the upload to more align with the actual artifact at rest.

Patch `create github release`

---

tools/Azure.Mcp.Tools.Cosmos/src/Commands/ContainerListCommand.cs
tools/Azure.Mcp.Tools.Cosmos/tests/Azure.Mcp.Tools.Cosmos.UnitTests/AccountListCommandTests.cs
tools/Azure.Mcp.Tools.Cosmos/tests/Azure.Mcp.Tools.Cosmos.UnitTests/ContainerListCommandTests.cs
tools/Azure.Mcp.Tools.Cosmos/tests/Azure.Mcp.Tools.Cosmos.UnitTests/DatabaseListCommandTests.cs
tools/Azure.Mcp.Tools.Cosmos/tests/Azure.Mcp.Tools.Cosmos.UnitTests/ItemQueryCommandTests.cs

Completes https://github.com/Azure/azure-mcp-pr/issues/298
Adds more unit tests for `Azure.Mcp.Tools.Cosmos`
https://github.com/Azure/azure-mcp-pr/issues/298

Add more unit tests for Azure.Mcp.Tools.Cosmos

---

eng/pipelines/templates/jobs/docker.yml
eng/pipelines/templates/jobs/release.yml

Docker's version variables weren't set as output, so following jobs couldn't use them
The version bump step wasn't overriding the default repo owner name of `Azure` to `microsoft` so it was producing the full PR target repo name `Azure/microsoft/mcp`

Fix issues in Docker and Version Bump steps

---

eng/scripts/AOT-Config.ps1
eng/tools/ToolDescriptionEvaluator/Program.cs
eng/tools/ToolDescriptionEvaluator/Run-ToolDescriptionEvaluator.ps1

Fixes broken AOT analysis and tool description evaluator scripts by updating project paths from non-existent CLI structure to actual server project location.
- Update AOT-Config.ps1 to reference `servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj`
- Fix ToolDescriptionEvaluator paths to use correct server executable location
- Replace `core/src/AzureMcp.Cli/` references with `servers/Azure.Mcp.Server/src/`
1. AOT 
2. Tool Evaluator

Update project paths for AOT analysis and tool description evaluator

---

.vscode/cspell.json
eng/pipelines/templates/common.yml
eng/pipelines/templates/jobs/sign-and-pack-vsix.yml

Fixed pattern matching for .p7s files for VSIX signing during release and added a verify step.
N/A

Fix VSIX signing and add "Verify VSIX Signing" step

---

eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updated CHANGELOGs ahead of 0.5.11 release
N/A

Prepare `0.5.11` release

---

eng/pipelines/templates/common.yml
servers/Azure.Mcp.Server/build.yml

Add missing parameter from build.yml down to release.yml

Add IncludeNative to server build.yml

---

eng/pipelines/templates/jobs/initialize.yml
eng/pipelines/templates/jobs/live-test.yml
eng/scripts/Deploy-TestResources.ps1
eng/scripts/Get-ProjectProperties.ps1
eng/scripts/Get-ToolsToTest.ps1
eng/scripts/Test-Code.ps1

Deploy-TestResources wasn't updated to support the new tools/ paths.
This changes the parameter from 'Area' to 'Tool' and 'Path'.
```
Deploy-TestResources.ps1 -Path Azure.Mcp.Tools.*
Deploy-TestResources.ps1 -Path storage
Deploy-TestResources.ps1 -Path core/Azure.Mcp.Core
```
fixes #38

Add Path and Tool parameters to DeployTestResources

---

core/Azure.Mcp.Core/tests/Azure.Mcp.Core.LiveTests/CommandTests.cs
servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.AzureBestPractices/src/Resources/azure-functions-deployment-best-practices.txt
tools/Azure.Mcp.Tools.AzureBestPractices/tests/Azure.Mcp.Tools.AzureBestPractices.UnitTests/BestPracticesCommandTests.cs

Add instructions about consumption plan for azure functions deployment best practices
N/A

Add instructions about consumption plan for azure functions deployment best practices

---

.devcontainer/devcontainer.json
.gitignore
global.json

Fix so .NET 9 build works while still specifying the preview version of 10
Suggested by .NET team

Fix devcontainer for .NET 9 builds and .NET 10 preview

---

.github/ISSUE_TEMPLATE/01_azure_mcp_onboard_request.yml
.github/ISSUE_TEMPLATE/02_mcp_server_request.yml
CATALOG.md
README.md

1. Fix project reference in `Azure MCP Server onboarding` issue template
2. Add a new `MCP Server onboarding` issue template
3. Move list of Microsoft MCP Servers to a new `CATALOG.md`
4. Update `README.md` with direct links to Azure MCP Server key files, and establish a v0 pattern for more MCP Servers to follow

Fix github issue templates and revise README.md / CATALOG.md

---

.github/CODEOWNERS

Added @microsoft/azure-mcp as codeowner for Azure Lustre

Added @microsoft/azure-mcp as Code Owner for Azure Lustre

---

servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.Aks/src/Commands/AksJsonContext.cs
tools/Azure.Mcp.Tools.Aks/src/Models/NodePool.cs
tools/Azure.Mcp.Tools.Aks/src/Services/AksService.cs
tools/Azure.Mcp.Tools.Aks/tests/Azure.Mcp.Tools.Aks.LiveTests/NodepoolCommandTests.cs
tools/Azure.Mcp.Tools.Aks/tests/Azure.Mcp.Tools.Aks.LiveTests/NodepoolGetCommandTests.cs
tools/Azure.Mcp.Tools.Aks/tests/Azure.Mcp.Tools.Aks.UnitTests/Nodepool/NodepoolGetCommandTests.cs
tools/Azure.Mcp.Tools.Aks/tests/Azure.Mcp.Tools.Aks.UnitTests/Nodepool/NodepoolListCommandTests.cs

Enhance AKS nodepool information with comprehensive properties
- Add detailed nodepool properties including disk configuration, scaling settings, and node metadata
- Expand NodePool model with 20+ new properties for complete cluster visibility
- Enhance unit and live tests to validate new properties
- Improve property naming consistency (NodeCount -> Count, NodeVmSize -> VmSize)

Enhance AKS nodepool information with comprehensive properties

---

core/Azure.Mcp.Core/src/Areas/Server/Commands/ServiceCollectionExtensions.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ServiceStartCommand.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/CommandFactoryToolLoader.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/ToolLoaderOptions.cs
core/Azure.Mcp.Core/src/Areas/Server/Options/ServiceOptionDefinitions.cs
core/Azure.Mcp.Core/src/Areas/Server/Options/ServiceStartOptions.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Server/Commands/ToolLoading/CommandFactoryToolLoaderTests.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Server/ServiceStartCommandTests.cs
docs/azmcp-commands.md

Add support for insecure-disable-elicitation
@[xiangyan99](https://github.com/microsoft/mcp/commits?author=xiangyan99)
xiangyan99 committed

Add support for insecure-disable-elicitation

---

tools/Fabric.Mcp.Tools.PublicApi/src/Fabric.Mcp.Tools.PublicApi.csproj

Fixes #107
This was left over from when we added Fabric.  VS wasn't building, so removing it.  It now builds and tests pass.

Remove System.Text.Json package reference from project

---

docs/azmcp-commands.md
docs/e2eTestPrompts.md
eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/src/Azure.Mcp.Server.csproj
tools/Azure.Mcp.Tools.KeyVault/src/KeyVaultSetup.cs
tools/Azure.Mcp.Tools.KeyVault/tests/Azure.Mcp.Tools.KeyVault.LiveTests/KeyVaultCommandTests.cs

Updates documentation ahead of the new release, as well as the project version (to `0.8.0`).
Also re-enables the `azmcp keyvault get key` and `azmcp keyvault get secret` commands.
N/A

Prepare 0.8.0 release

---

eng/pipelines/templates/common.yml
eng/pipelines/templates/jobs/build.yml
eng/pipelines/templates/jobs/docker/release-docker.yml
eng/pipelines/templates/jobs/initialize.yml
eng/pipelines/templates/jobs/integration.yml
eng/pipelines/templates/jobs/npm/pack-npm.yml
eng/pipelines/templates/jobs/npm/release-npm.yml
eng/pipelines/templates/jobs/nuget/pack-and-sign-nuget.yml
eng/pipelines/templates/jobs/nuget/release-nuget.yml
eng/pipelines/templates/jobs/release.yml
eng/pipelines/templates/jobs/sign-and-pack.yml
eng/pipelines/templates/jobs/vsix/pack-and-sign-vsix.yml
eng/pipelines/templates/jobs/vsix/release-vsix.yml
eng/pipelines/templates/variables/globals.yml

Removes the complexity of using an output variable for the version suffix by creating a global variable.
Replaces $(PipelineArtifactName) based artifact names with consistent static names:
- build_{platform}
- binaries_signed
- packages_npm
- packages_vsix_signed
- packages_nuget_signed
- docker_staged

Use static artifact names and version suffix veriable

---

eng/pipelines/templates/common.yml
eng/pipelines/templates/jobs/release.yml
servers/Azure.Mcp.Server/build.yml
servers/Fabric.Mcp.Server/build.yml
servers/Template.Mcp.Server/build.yml

Instead of inferring the release target and dynamic version settings based on the branch being built, we'll now rely on 2 parameters:
- PublishTarget (public, internal, none) if and where we're publishing
- IsTestPipeline (always build a dynamic prerelease version)
Public builds won't make a prerelease tagged version, except for test pipelines, which always build prerelease versions
IsTestPipeline also controls if we're going to automatically close the Bump Version PR

Allow any branch to be built for release

---

docs/azmcp-commands.md
docs/e2eTestPrompts.md
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/README.md
tools/Azure.Mcp.Tools.Sql/src/Commands/Database/DatabaseRenameCommand.cs
tools/Azure.Mcp.Tools.Sql/src/Commands/SqlJsonContext.cs
tools/Azure.Mcp.Tools.Sql/src/Options/Database/DatabaseRenameOptions.cs
tools/Azure.Mcp.Tools.Sql/src/Options/SqlOptionDefinitions.cs
tools/Azure.Mcp.Tools.Sql/src/Services/ISqlService.cs
tools/Azure.Mcp.Tools.Sql/src/Services/SqlService.cs
tools/Azure.Mcp.Tools.Sql/src/SqlSetup.cs
tools/Azure.Mcp.Tools.Sql/tests/Azure.Mcp.Tools.Sql.UnitTests/Database/DatabaseRenameCommandTests.cs

Add `azmcp sql db rename` command and unit tests

Add `azmcp sql db rename` command and unit tests

---

core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Client/MockClientTests.cs

We were getting an exception when calling mcp with an invalid tool name.  I don't see that error, but I'm adding a unit test.  We also have a live test covering the scenario.
Fixes #208

Add tests for invalid tool requests handling

---

core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/BaseToolLoader.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/ServerToolLoader.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/SingleProxyToolLoader.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Server/Commands/ToolLoading/BaseToolLoaderTests.cs
servers/Azure.Mcp.Server/CHANGELOG.md

When running in `namespace` mode or leveraging built in external servers like `documentation` and `azd` MCP features for sampling and elicitation are not enabled. 
This PR correctly sets the sampling and elicitation capabilities when generating the MCP clients and forwards requests along to the original MCP host..
Resolves #214

Adds support to proxy MCP capabilities when child servers leverage sampling or elicitation

---

servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.Kusto/src/Services/KustoService.cs
tools/Azure.Mcp.Tools.Kusto/tests/Azure.Mcp.Tools.Kusto.LiveTests/KustoCommandTests.cs

…alls
fix table schema issue and also adding live tests for missing Kusto calls
when table schema tool is running it responses only with headers which is generic info and actual schema of the table is returned to the clients.
[[`[Link to the GitHub issue this PR addresses]`](https://github.com/microsoft/mcp/issues/530)](https://github.com/microsoft/mcp/issues/530)

fix table schema issue and also adding live tests for missing Kusto calls

---

tools/Azure.Mcp.Tools.Kusto/src/Commands/ClusterGetCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/ClusterListCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Options/ClusterGetOptions.cs
tools/Azure.Mcp.Tools.Kusto/src/Options/ClusterListOptions.cs

Update the command options for both `kusto-cluster-list` and `kusto-cluster-ge`t as part of the fix for https://github.com/microsoft/mcp/issues/549.
https://github.com/microsoft/mcp/issues/549

Correct the command options for Kusto clust get and list tool

---

core/Azure.Mcp.Core/src/Areas/Subscription/Commands/SubscriptionListCommand.cs

Enhance the tool description for Cloud Architect to get a confidence score of >0.4
https://github.com/microsoft/mcp/issues/262

Enhance Tool description for listing azure subscriptions

---

Directory.Packages.props
tools/Azure.Mcp.Tools.Acr/src/Azure.Mcp.Tools.Acr.csproj
tools/Azure.Mcp.Tools.Acr/src/Commands/AcrJsonContext.cs
tools/Azure.Mcp.Tools.Acr/src/Services/AcrService.cs
tools/Azure.Mcp.Tools.Acr/src/Services/IAcrService.cs
tools/Azure.Mcp.Tools.Acr/src/Services/Models/ContainerRegistryData.cs
tools/Azure.Mcp.Tools.Acr/src/Services/Models/ContainerRegistryProperties.cs

This PR addresses part of the issue tracked in https://github.com/microsoft/mcp/issues/226 by updating the ACR tool to eliminate its dependency on Azure.ResourceManager.ContainerRegistry.
As a result, it reduces the MCP agent size by approximately 1.46 MB.
https://github.com/microsoft/mcp/issues/226

Using ARG query to support ACR resource read operations

---

AGENTS.md
CONTRIBUTING.md
eng/scripts/Build-Docker.ps1
servers/Azure.Mcp.Server/README.md
servers/Azure.Mcp.Server/TROUBLESHOOTING.md

- Updates instructions for building Docker container locally.
- Updates Docker README section to be more concise.
- Adds instructions for using Azure Entra ID on Docker.
N/A

Updates instructions for Docker

---

tools/Azure.Mcp.Tools.Foundry/src/Commands/AgentsConnectCommand.cs
tools/Azure.Mcp.Tools.Foundry/src/Commands/DeploymentsListCommand.cs
tools/Azure.Mcp.Tools.Foundry/src/Commands/ModelDeploymentCommand.cs

Enhance tool description for AI Foundry to have a confidence score of >0.4
https://github.com/microsoft/mcp/issues/250

Enhance tool description for AI Foundry

---

tools/Azure.Mcp.Tools.Cosmos/src/Commands/ItemQueryCommand.cs

Enhance the tool description for cosmos to reduce ambiguity in the Cosmos Item Query command. The rest of the tools in Cosmos are doing good in terms of confidence score and do not fall in the ambiguous range. 
**After Change**
**Before Change**
https://github.com/microsoft/mcp/issues/624

Enhance the tool description for cosmos to reduce ambiguity

---

docs/azmcp-commands.md
servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.KeyVault/src/KeyVaultSetup.cs

The Key Vault settings get command is supposed to show up as `azmcp_keyvault_admin_settings_get`, but was showing up as `azmcp_keyvault_admin_get`. This PR corrects that.
N/A

Fix the name of the Key Vault settings get command

---

eng/pipelines/templates/jobs/build.yml

We’ve agreed internally that AOT build validation will only need to run on Linux x64.

Limiting native AOT build to Linux x64

---

core/Azure.Mcp.Core/src/Areas/Tools/Commands/ToolsListCommand.cs
core/Azure.Mcp.Core/src/Commands/ToolMetadata.cs
core/Azure.Mcp.Core/src/Models/Command/CommandInfo.cs
core/Azure.Mcp.Core/src/Models/ModelsJsonContext.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Tools/UnitTests/ToolsListCommandTests.cs
servers/Azure.Mcp.Server/CHANGELOG.md

#564
Added the support to return meta data in `tool list` command
Now `azmcp tools list` command also shows something like
"metadata": {
"destructive": true,
"idempotent": true,
"openWorld": false,
"readOnly": false,
"secret": false,
"localRequired": false
}

Added the support to return meta data in `tool list` command

---

docs/e2eTestPrompts.md
eng/tools/ToolDescriptionEvaluator/prompts.json
eng/tools/ToolDescriptionEvaluator/results.md
eng/tools/ToolDescriptionEvaluator/tools.json
servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.Kusto/src/Commands/ClusterGetCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/ClusterListCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/DatabaseListCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/QueryCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/SampleCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/TableListCommand.cs
tools/Azure.Mcp.Tools.Kusto/src/Commands/TableSchemaCommand.cs

This PR updates the descriptions of Kusto tools to get them all above the 0.4 cosine similarity threshold, make them the top choice and reduce ambiguity vs. the second choice.
#253

Enhance descriptions for Kusto tools

---

eng/dnx/nuspec/README.md
eng/vscode/CHANGELOG.md
servers/Azure.Mcp.Server/CHANGELOG.md

Updated CHANGELOGs and the NuGet README
N/A

Prepare `0.8.4` release

---

core/Azure.Mcp.Core/src/Services/Azure/Authentication/TimeoutTokenCredential.cs
servers/Azure.Mcp.Server/CHANGELOG.md

It is by design that InteractiveBrowserCredential does not work on MacOS.
Catch the error and give a better error message.

Update error message for InteractiveBrowserCredential on MacOS

---

docs/azmcp-commands.md
eng/pipelines/templates/jobs/live-test.yml
servers/Azure.Mcp.Server/CHANGELOG.md
servers/Azure.Mcp.Server/README.md
tools/Azure.Mcp.Tools.AzureManagedLustre/src/AzureManagedLustreSetup.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Commands/AzureManagedLustreJsonContext.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Commands/BaseAzureManagedLustreCommand.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Commands/FileSystem/FileSystemCreateCommand.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Commands/FileSystem/FileSystemUpdateCommand.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Options/AzureManagedLustreOptionDefinitions.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Options/FileSystem/FileSystemCreateOptions.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Options/FileSystem/FileSystemUpdateOptions.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Services/AzureManagedLustreService.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/src/Services/IAzureManagedLustreService.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/tests/Azure.Mcp.Tools.AzureManagedLustre.LiveTests/AzureManagedLustreCommandTests.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/tests/Azure.Mcp.Tools.AzureManagedLustre.UnitTests/FileSystem/FileSystemCreateCommandTests.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/tests/Azure.Mcp.Tools.AzureManagedLustre.UnitTests/FileSystem/FileSystemUpdateCommandTests.cs
tools/Azure.Mcp.Tools.AzureManagedLustre/tests/test-resources-post.ps1
tools/Azure.Mcp.Tools.AzureManagedLustre/tests/test-resources.bicep

Adds the following Azure Managed Lustre commands:
- `azmcp-azuremanagedlustre-filesystem-create`: Create an Azure Managed Lustre filesystem. [[#50](https://github.com/microsoft/mcp/issues/50)]
Relates to:
- [Add `azmcp azuremanagedlustre filesystem create`](https://github.com/microsoft/mcp/issues/50)

[Azure MCP] Add command: `azmcp azuremanagedlustre filesystem create`

---

core/Azure.Mcp.Core/src/Areas/Server/Commands/ServiceCollectionExtensions.cs
core/Azure.Mcp.Core/src/Areas/Server/Commands/ToolLoading/NamespaceToolLoader.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Server/Commands/ServiceCollectionExtensionsTests.cs
core/Azure.Mcp.Core/tests/Azure.Mcp.Core.UnitTests/Areas/Server/Commands/ToolLoading/NamespaceToolLoaderTests.cs

Today, when we start `azmcp` in default mode (which is equivalent to `--mode namespace` , the default mode for VS Code as well), the server creates a new `azmcp` process for every command group (child namespace name) and uses a stdio channel to invoke commands. 
Below is the output of all azmcp processes after I used the "Azure MCP Server" (via VS Code extension) in Copilot and tried a few tool calls. Each `azmcp` process uses approximately 80-140 MB of memory.
| Process ID | Memory   | Command |
|------------|----------|---------|
| 56044 | 157.9 MB | `server/azmcp server start --mode namespace` |
| 56326 | 137.1 MB | `server/azmcp server start --mode all --namespace subscription` |
| 56441 | 180.9 MB | `server/azmcp server start --mode all --namespace marketplace` |
| 56476 | 138.5 MB | …

NamespaceToolLoader: the tool loader that supports namespace mode without creating child azmcp processes

---

servers/Azure.Mcp.Server/CHANGELOG.md
tools/Azure.Mcp.Tools.Acr/src/Services/AcrService.cs
tools/Azure.Mcp.Tools.AppConfig/src/Services/AppConfigService.cs
tools/Azure.Mcp.Tools.EventHubs/src/Services/EventHubsService.cs
tools/Azure.Mcp.Tools.Kusto/src/Services/KustoService.cs
tools/Azure.Mcp.Tools.Sql/src/Services/SqlService.cs
tools/Azure.Mcp.Tools.Storage/src/Services/StorageService.cs

This PR fixes a problem for EventHubs and ACR where the `additionalFilter` value was being passed as `tableName` after this last parameter was introduced in [PR #607](https://github.com/microsoft/mcp/pull/607/files#diff-90873735813f341180ede934ed060e63a185c05391f34dfe13efc4f38ffc4dacR89).
I explicitly specified all parameter names as well, to prevent these references from breaking in the future if new parameters are added.
Fixes https://github.com/microsoft/mcp/issues/727

Update ExecuteSingleResourceQueryAsync references to include parameter names
